package Utilisateurs;

import Client.ClientTemplate;
import Entity.Utilisateur;
import Services.UtilisateurServices;
import com.codename1.components.ImageViewer;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Command;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.NavigationCommand;
import com.codename1.ui.RadioButton;
import com.codename1.ui.Slider;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.plaf.Border;
import com.codename1.ui.plaf.Style;
import com.codename1.ui.util.UIBuilder;
import org.mindrot.jbcrypt.BCrypt;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Login {

    private Resources theme;
    private Form current, f1;
    private Container c1;
    private UIBuilder uiBuilder;
    private String resultat;

    private Form home;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }

        //create and build the home Form
        UIBuilder.registerCustomComponent("ImageViewer", ImageViewer.class); 
        uiBuilder = new UIBuilder (); 
        c1 =uiBuilder.createContainer(theme, "Home");
        TextField login = (TextField)uiBuilder.findByName("login", c1);
        TextField password = (TextField)uiBuilder.findByName("password", c1);
        Button bt_conn =(Button)uiBuilder.findByName(("bt_conn"), c1);
        Button bt_oublier = new Button("Mot de passe oublié ?");
        bt_oublier.getAllStyles().setBorder(Border.createEmpty()); 
        bt_oublier.getAllStyles().setFgColor(0x4285f4); 
        bt_oublier.getAllStyles().setTextDecoration(Style.TEXT_DECORATION_UNDERLINE);
        
        bt_conn.addActionListener(e-> //button connexion
        {
            if ((login.getText()=="") && (password.getText()==""))
                Dialog.show("Error!", "Saisie le nom d'utilisateur et mot de passe", "Ok", null);
            else
            {
                UtilisateurServices userService = new UtilisateurServices();
                Utilisateur user = userService.findUser(login.getText());
                if (user.getId() == null)
                {
                    login.setText("");
                    password.setText("");
                    Dialog.show("Error!", "Login ou mot de passe incorrect!", "Ok", null);
                }
                else
                {
                    String hashed =user.getPassword().substring(0, 2)+"a"+user.getPassword().substring(3);
                    if (BCrypt.checkpw(password.getText(),hashed)) 
                    {
                        if (user.getRoles().equals("a:1:{i:0;s:11:\"ROLE_CLIENT\";}"))
                        {
                            Client.ClientTemplate clientTemplate = new ClientTemplate();
                            clientTemplate.startClientTemplate();
                        }
                    }

                }
                
            }
        });
        bt_oublier.addActionListener(l->
            {
                System.out.println("Utilisateurs.Login.start()");
                TokenConfirmation tokenConf = new TokenConfirmation();
                tokenConf.start();
            });
        c1.add(bt_oublier); 
        home=(Form)c1;
        home.show();
    }

    protected void setBackCommand(Form f) {
        Command back = new Command("") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                home.showBack();
            }

        };
        Image img = FontImage.createMaterial(FontImage.MATERIAL_ARROW_BACK, UIManager.getInstance().getComponentStyle("TitleCommand"));
        back.setIcon(img);
        f.getToolbar().addCommandToLeftBar(back);
        f.getToolbar().setTitleCentered(true);
        f.setBackCommand(back);
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

}
